### ISSUE TITLE
Intenral: Can't save large debug traces

### ISSUE THREAD

**Issue by TheIronWolfModding** [mrbelowski/CrewChiefV4#104]
at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
at System.IO.StreamWriter.Write(String value)
at System.Xml.XmlTextWriter.WriteStartElement(String prefix, String localName, String ns)
at System.Xml.Serialization.XmlSerializationWriter.Wr iteElementStringRaw(String localName, String ns, String value, XmlQualifiedName xsiType)
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlS erializationWriterRF2StructWrapperArray.Write4_rF2 VehScoringInfo(String n, String ns, rF2VehScoringInfo o, Boolean needType)
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlS erializationWriterRF2StructWrapperArray.Write5_rF2 State(String n, String ns, rF2State o, Boolean needType)
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlS erializationWriterRF2StructWrapperArray.Write6_RF2 StructWrapper(String n, String ns, RF2StructWrapper o, Boolean isNullable, Boolean needType)
at Microsoft.Xml.Serialization.GeneratedAssembly.XmlS erializationWriterRF2StructWrapperArray.Write7_Arr ayOfRF2StructWrapper(Object o)

stream was too long

This article suggests to replace MemoryStream with FileStream, I'll try that when I can. http://stackoverflow.com/questions/3...data-to-stream

Also, I am wondering if we can make all of this faster/smaller, by for example saving only delta's between updates.   On other hand, .zip takes care of duplication in the stream, so might not be worth trouble.

**Comment by TheIronWolfModding** [comment]
Fixed in PR https://github.com/mrbelowski/CrewChiefV4/pull/105
