### ISSUE TITLE
Trouble launching version 4.9.5.2 with nAudio playback

### ISSUE THREAD

**Issue by lowlyocean** [mrbelowski/CrewChiefV4#335]
I tried from command line, no GUI opens and also nothing printed. Last thing I remember doing is turning on nAudio for both playback and voice recognition. Tried cleaning CrewChiefv4 folder in My Documents and reinstalling with no success. Can't locate any log. Any ideas?

**Comment by lowlyocean** [comment]
I deleted the user.config file from Local Appdata and was able to launch. I can set nAudio for voice recognition and restart succesfully. But if I try setting naudio playback, the app won't launch.

**Comment by lowlyocean** [comment]
I had forgotten to install SpeechPlatformRuntime.msi and MSSpeech_SR_en-US_TELE.msi. After installing these, I was able to enable nAudio playback.

**Comment by mrbelowski** [comment]
i'm going to reopen this because we're supposed to catch and report this kind of error, not just silently crash. It's also puzzling that a missing SRE component would prevent nAudio playback initialisation.

Thanks for the info

**Comment by mrbelowski** [comment]
Hmm... I can't reproduce this on the current live version. If I uninstall the speech recogniser the app shows the warning popup, even if I have nAudio enabled

**Comment by lowlyocean** [comment]
Application: CrewChiefV4.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.DirectoryNotFoundException
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare)
   at NAudio.Wave.WaveFileReader..ctor(System.String)
   **at CrewChiefV4.Audio.NAudioBackgroundPlayer.initReader(System.String)**
   at CrewChiefV4.Audio.NAudioBackgroundPlayer.initialise(System.String)
   at CrewChiefV4.Audio.AudioPlayer.initialise()
   at CrewChiefV4.CrewChief..ctor()
   at CrewChiefV4.MainWindow..ctor()
   at CrewChiefV4.Program.Main()

**Comment by mrbelowski** [comment]
the up-coming release already has some nAudio initialisation checks added which would have caught this error and allowed the app to start up using WMP as the background player instead, so I think it can be safely closed.

Thanks for all the info
